site_name: AI in robotics
theme:
  name: swan
  logo: img/logo.png
  favicon: img/logo.png
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
extra_css:
  - css/tabs.css
nav:
  - Введение: index.md
  - Работа в PyCharm: pycharm.md
  - Способы внедрения:
      - Подходы к внедрению: hardware.md
      - Telegram Bot + AI: tgai.md
  - Фреймфорки:
    - YOLO: yolo.md
    - MediaPipe: mediapipe.md
  - Технологии:
    - Распознавание лица: face_recognition.md
    - Распознавание речи: speech-to-text.md
    - Синтез речи: tts.md
    - Распознавание ключевых слов: KWS.md
    - Большие языковые модели: llm.md
  - Hardware:
    - Python + Arduino: py+ard.md
    - Jetson Nano: jetson.md
    - Raspberry Pi: raspberry.md
    - XBOX Kinect: kinect.md
    - ИИ камеры: cams.md
  - Работа с API: api.md
  - ИИ помощники: assistants.md
  - На будущее: todo.md